Meetings Project/Models/ErrorViewModel.cs
namespace Meetings_Project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Meetings Project/Models/Meeting.cs
namespace Meetings_Project.Models
{
    public class Meeting
    {
        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public int Duration { get; set; } // In minutes

        public virtual Room Room { get; set; }

        public virtual ICollection<Person> Persons { get; set; }
    }
}

Meetings Project/Models/MeetingContext.cs
using Microsoft.EntityFrameworkCore;

namespace Meetings_Project.Models
{
    public class MeetingContext : DbContext
    {
        public DbSet<Person> Persons { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Meeting> Meetings { get; set; }

        public string DbPath { get; }

        public MeetingContext()
        {
            var folder = Environment.SpecialFolder.LocalApplicationData;
            var path = Environment.GetFolderPath(folder);
            DbPath = System.IO.Path.Join(path, "meetings.db");
        }

        // The following configures EF to create a Sqlite database file in the
        // special "local" folder for your platform.
        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite($"Data Source={DbPath}");

    }
}

Meetings Project/Models/NewMeeting.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Meetings_Project.Models
{
    public class NewMeeting
    {
        public NewMeeting()
        {
            //to start the user on the same time and day
            MeetingStart = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, 0, 0);
        }

        [Required]
        public int MeetingRoomId { get; set; }

        [Required]
        [MinLength(2)]
        public List<int> PersonIds { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime MeetingStart { get; set; }

        [Required]
        public int Duration { get; set; } // In Minutes
    }
}

Meetings Project/Models/Person.cs
namespace Meetings_Project.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

Meetings Project/Models/Room.cs
namespace Meetings_Project.Models
{
    public class Room
    {
        public int Id { get; set; }
        public string RoomName { get; set; }
    }
}

Meetings Project/Controllers/MeetingController.cs
using Meetings_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Meetings_Project.Controllers
{
    public class MeetingController : Controller
    {
        private readonly ILogger<MeetingController> _logger;
        private readonly MeetingContext _db;

        public MeetingController(ILogger<MeetingController> logger, MeetingContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Calendar()
        {
            var meetings = 
                _db.Meetings
                .Include(x => x.Persons)
                .Include(x => x.Room)
                .OrderBy(x => x.StartTime)
                .ToList();

            return View(meetings);
        }

        public IActionResult NewMeeting()
        {
            var newMeeting = new NewMeeting();

            PopulateNewMeetingViewData();
            return View(newMeeting);
        }

        [HttpPost]
        public IActionResult NewMeeting(NewMeeting newMeeting)
        {
            PopulateNewMeetingViewData();

            if (ModelState.IsValid)
            {

                //check for overlapping rooms

                var overlappingMeetings = _db.Meetings.Where(x =>
                    x.StartTime < newMeeting.MeetingStart.AddMinutes(newMeeting.Duration) &&
                    newMeeting.MeetingStart < x.StartTime.AddMinutes(x.Duration)).ToList();

                // Meeting room cannot be in use at this time
                if (overlappingMeetings.Where(x => x.Room.Id == newMeeting.MeetingRoomId).Any())
                {
                    var errorMeeting = overlappingMeetings.Where(x => x.Room.Id == newMeeting.MeetingRoomId).First();

                    //error
                    ModelState.AddModelError(string.Empty,
                        $"This meeting room is already in use at this time - {errorMeeting.StartTime} to {errorMeeting.StartTime.AddMinutes(errorMeeting.Duration)}");

                    return View(newMeeting);
                }

                //check for overlapping persons

                var overlappingPersons = overlappingMeetings
                    .SelectMany(x => x.Persons)
                    .Where(att => newMeeting.PersonIds.Contains(att.Id))
                    .Distinct().ToList();

                if (overlappingPersons.Any())
                {
                    foreach (var person in overlappingPersons)
                    {
                        //error
                        ModelState.AddModelError(string.Empty,
                         $"{person.FirstName} {person.LastName} is already in a meeting during this time.");

                    }

                    return View(newMeeting);
                }

                //create meeting

                var meeting = new Meeting
                {
                    StartTime = newMeeting.MeetingStart,
                    Duration = newMeeting.Duration,
                    Room = _db.Rooms.Where(x => x.Id == newMeeting.MeetingRoomId).First(),
                    Persons = _db.Persons.Where(x => newMeeting.PersonIds.Contains(x.Id)).ToList()
                };

                _db.Add(meeting);
                _db.SaveChanges();

                //return a success string, this will make the page show a success message
                ViewData["successMessage"] = $"Meeting set up at {meeting.StartTime} for {meeting.Duration} minutes";

            }

            return View(newMeeting);
        }

        private void PopulateNewMeetingViewData()
        {
            ViewData["persons"] = _db.Persons.ToList();
            ViewData["rooms"] = _db.Rooms.ToList();
        }
    }
}

Meetings Project/Views/Meeting/Calendar.cshtml
@model List<Meeting>


@functions{

    private string PersonListToStringList(List<Person> persons)
    {
        return string.Join(", ", persons.Select(x => $"{x.FirstName} {x.LastName}"));
    }

}

<h1>CALENDAR</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Meeting Id</th>
            <th scope="col">Start Time</th>
            <th scope="col">Duration</th>
            <th scope="col">Room</th>
            <th scope="col">Attendees</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var meeting in Model)
        {
        <tr>
            <th scope="row">@meeting.Id</th>
            <td>@meeting.StartTime</td>
            <td>@meeting.Duration minutes</td>
            <td>@meeting.Room.RoomName</td>
            <td>@PersonListToStringList(meeting.Persons.ToList())</td> 
        </tr>
        }
    </tbody>
    </table>

Meetings Project/Views/Meeting/NewMeeting.cshtml
@model Meetings_Project.Models.NewMeeting

@{
    var persons = ViewData["persons"] as List<Person>;
    var rooms = ViewData["rooms"] as List<Room>;

    var successMessage = ViewData["successMessage"] as string;
}

<h1>CREATE A NEW MEETING</h1>

@if (!string.IsNullOrEmpty(successMessage))
{
    <h2>@successMessage</h2>
    <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="Calendar">Check it out on the Calendar</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="NewMeeting">Create a new meeting</a>
}
else
{
    <form method="post" enctype="multipart/form-data" asp-controller="Meeting" asp-action="NewMeeting">

        <div class="row">
            <div asp-validation-summary="All">
            </div>
        </div>

        <div class="form-group">
            <label for="meetingStart">Meeting start date and time</label>
            <input asp-for="MeetingStart" class="form-control" type="datetime-local" id="meetingStart">
        </div>

        <div class="form-group">
            <label for="duration">Meeting duration (minutes)</label>
            <select asp-for="Duration" class="form-control" id="duration" name="duration">
                <option>Select a meeting duration</option>
                <option value="15">15</option>
                <option value="30">30</option>
                <option value="45">45</option>
                <option value="60">60</option>
            </select>
        </div>

        <div class="form-group">
            <label for="meetingRoomId">Room Select:</label>
            <select asp-for="MeetingRoomId" class="form-control" id="meetingRoomId" name="meetingRoomId">
                <option>Select a meeting room</option>
                @foreach (var room in rooms)
                {
                    <option value="@room.Id">@room.RoomName</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label for="personIds">Example multiple select (ctrl click to select multiple)</label>
            <select asp-for="PersonIds" multiple class="form-control" id="personIds" name="personIds">
                @foreach (var person in persons)
                {
                    <option value="@person.Id">@person.FirstName @person.LastName</option>
                }
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

}

Meetings Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meetings Project By Jason Wood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meetings_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Meeting" asp-action="Index">Meetings Project By Jason Wood</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="Calendar">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="NewMeeting">Create Meeting</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
      </html>